import { App, Avatar, Button, Card, Empty, Form, Input, Modal, Select, Segmented, Spin, Tag, Tooltip } from 'antd';
import { EditOutlined, FileTextOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { useCallback, useEffect, useState } from 'react';
import type { FontLayoutLibraryTemplate, ProductCategory, Shop } from '@shared/domain';
import { browserAlbumApi } from '../../api';
import { ImageMapEditor } from '../../image-map-editor/editor-entry';
import type { ImageMapFontLayoutLayerData, ImageMapSizeSchemeValue } from '../../image-map-editor/editor-entry';
import { applyTextFont, loadTextFonts } from '../fontRuntime';

type Props = { shops: Shop[]; products: ProductCategory[]; selectedShopId?: number; selectedProductId?: number };
const blankLayers = (canvasRows: 1 | 2 = 1): ImageMapFontLayoutLayerData => ({
  objects: [{ id: 'workarea', canvasRows }],
  animations: [],
  styles: [],
  dataSources: []
});
const sizeFor = (product?: ProductCategory): Partial<ImageMapSizeSchemeValue> => {
  const spec = product?.commonSpecValues?.[0];
  const bleed = typeof spec?.bleed === 'object' ? spec.bleed.left : spec?.bleed;
  const pageCount = spec?.pageCount || 50;
  const pageRules = product?.spineWidthMode === 'page_count_table' ? product.spineWidthPageRules?.items ?? [] : [];
  const matchedRule = pageRules.slice().sort((left, right) => left.pageCount - right.pageCount).find(rule => product?.spineWidthPageRules?.matchStrategy === 'floor' ? rule.pageCount <= pageCount : product?.spineWidthPageRules?.matchStrategy === 'exact' ? rule.pageCount === pageCount : rule.pageCount >= pageCount)
    ?? pageRules.slice().sort((left, right) => right.pageCount - left.pageCount)[0];
  return { id: spec?.id || spec?.label || '默认规格', label: spec?.label || '默认规格', unit: spec?.unit || 'in', sideWidth: spec?.sideWidth || 9, sideHeight: spec?.sideHeight || 6, bleed: bleed || 0, separateBleed: typeof spec?.bleed === 'object', horizontalBleed: typeof spec?.bleed === 'object' ? spec.bleed.left : undefined, verticalBleed: typeof spec?.bleed === 'object' ? spec.bleed.right : undefined, spineWidth: matchedRule?.spineWidth ?? spec?.spineWidth ?? 0, spineBleed: matchedRule?.spineBleed ?? spec?.spineBleed ?? 0, spineWidthMode: product?.spineWidthMode === 'range' ? 'fixed' : 'by_page_count', ...(product?.spineWidthMode === 'formula' && product.spineWidthFormula ? { spineWidthFormula: product.spineWidthFormula } : {}), minSpineWidth: spec?.minSpineWidth || 0, maxSpineWidth: spec?.maxSpineWidth || 0, pageCount, pageCountOptions: spec?.pageCountOptions?.length ? spec.pageCountOptions : [pageCount], paperThickness: spec?.paperThickness || 0, coverSafeDistance: product?.coverSafeDistance, backCoverSafeDistance: product?.backCoverSafeDistance, spineSafeDistance: product?.spineSafeDistance };
};
const record = (value: unknown): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
function toLayers(elements: Record<string, unknown>[] = []): ImageMapFontLayoutLayerData { return { ...blankLayers(), objects: elements.map(item => { const frame = record(item.frame); const font = record(item.font); const style = record(item.style); const transform = record(item.transform); const asset = record(item.asset); const text = String(item.type || 'text') === 'text'; return { id: String(item.id || item.name || crypto.randomUUID()), type: text ? 'textbox' : 'image', name: item.name, text: item.text ?? '', left: Number(frame.x) || 0, top: Number(frame.y) || 0, width: Math.max(1, Number(frame.width) || 120), height: Math.max(1, Number(frame.height) || 42), angle: Number(transform.rotation_deg) || 0, fontSize: Number(font.size_px) || 42, fontFamily: String(font.font_family || font.font_name || 'Arial'), fontWeight: font.bold ? 'bold' : 'normal', fontStyle: font.italic ? 'italic' : 'normal', fill: String(style.fill_color || '#000000'), src: String(asset.url || asset.file_path || '') }; }) }; }
function toElements(layers: ImageMapFontLayoutLayerData, previous: Record<string, unknown>[] = []) { const byId = new Map(previous.map(item => [String(item.id), item])); return layers.objects.filter(item => item.id !== 'workarea').map(item => { const prior = byId.get(String(item.id)) || {}; const text = ['textbox', 'i-text'].includes(String(item.type).toLowerCase()); return { ...prior, id: String(item.id || crypto.randomUUID()), type: text ? 'text' : 'image', ...(text ? { text: String(item.text || ''), font: { ...record(prior.font), size_px: Number(item.fontSize) || 42, font_family: String(item.fontFamily || 'Arial'), bold: item.fontWeight === 'bold', italic: item.fontStyle === 'italic' } } : { asset: record(prior.asset) }), frame: { x: Number(item.left) || 0, y: Number(item.top) || 0, width: Math.max(1, Number(item.width) || 1) * (Number(item.scaleX) || 1), height: Math.max(1, Number(item.height) || 1) * (Number(item.scaleY) || 1) }, style: { ...record(prior.style), fill_color: String(item.fill || '#000000') }, transform: { ...record(prior.transform), rotation_deg: Number(item.angle) || 0 } }; }); }
function LayoutCard({ template, onOpen }: { template: FontLayoutLibraryTemplate; onOpen: () => void }) { return <Card className="template-library-card font-layout-template-card" hoverable onClick={onOpen}><div className="template-library-card-preview">{template.previewImage ? <img className="template-library-card-preview-image" src={template.previewImage} alt={`${template.name || '未命名字体布局'}预览图`} /> : <Avatar shape="square" icon={<FileTextOutlined />} />}</div><div className="template-library-card-head"><div className="template-library-card-title"><strong>{template.name || '未命名字体布局'}</strong></div><Tooltip title="编辑字体布局"><Button type="text" icon={<EditOutlined />} onClick={event => { event.stopPropagation(); onOpen(); }} /></Tooltip></div><div className="template-library-card-stats"><div><span>图层</span><strong>{template.layers.objects.filter(item => item.id !== 'workarea').length}</strong></div><div><span>来源产品</span><strong>{template.productCategoryName || '当前产品'}</strong></div></div><div className="template-library-card-footer"><span>字体布局 ID：{template.id}</span></div></Card>; }

export default function FontLayoutsPage({ shops, products, selectedShopId, selectedProductId }: Props) {
  const { message } = App.useApp(); const [templates, setTemplates] = useState<FontLayoutLibraryTemplate[]>([]); const [loading, setLoading] = useState(false); const [editing, setEditing] = useState<FontLayoutLibraryTemplate>(); const [editingScheme, setEditingScheme] = useState<Partial<ImageMapSizeSchemeValue>>(); const [editorLoading, setEditorLoading] = useState(false); const [createOpen, setCreateOpen] = useState(false); const [name, setName] = useState(''); const [createShopId, setCreateShopId] = useState<number>(); const [createCanvasRows, setCreateCanvasRows] = useState<1 | 2>(1); const [saving, setSaving] = useState(false); const [version, setVersion] = useState(0); const product = products.find(item => item.id === selectedProductId); const shopId = selectedShopId ?? product?.shopIds?.[0] ?? shops[0]?.id;
  const load = useCallback(async () => { if (!shopId) return; setLoading(true); try { const all = await browserAlbumApi.fontLayoutLibrary.list({ shopId, productId: selectedProductId, limit: 100, offset: 0 }); setTemplates(all); } catch (error) { message.error(error instanceof Error ? error.message : String(error)); } finally { setLoading(false); } }, [message, selectedProductId, shopId]); useEffect(() => { void load(); }, [load, version]);
  if (!product || !selectedProductId) return <section className="panel template-library-page"><Empty description="请从左侧选择产品" /></section>;
  const openEditor = async (item: FontLayoutLibraryTemplate) => { setEditorLoading(true); try { const detail = await browserAlbumApi.fontLayoutLibrary.get(item.id); setEditingScheme(sizeFor(product)); setEditing(detail); } catch (error) { message.error(error instanceof Error ? error.message : String(error)); } finally { setEditorLoading(false); } };
  if (editing) return <div className="image-map-editor-test-page font-layouts-page"><ImageMapEditor key={editing.id} initialTheme="light" basicInfoEntityLabel="字体布局" saveButtonLabel="保存字体布局" alwaysEnableSave hideJsonImportExport initialBasicInfo={{ shopId: editing.shopId, templateName: editing.name }} templatePreviewImage={editing.previewImage} initialLayers={editing.layers} initialSizeSchemes={[editingScheme || sizeFor(product)]} simplifiedSizeScheme skipTextSafeAreaCheck={product.useSafeDistance === false} hiddenActivities={['fontLayouts']} shops={shops.map(shop => ({ value: shop.id, label: shop.shopName || shop.shop || '未命名店铺' }))} applyTextFont={applyTextFont} loadTextFonts={loadTextFonts} uploadPreviewImage={file => browserAlbumApi.oss.uploadImage(file)} onPreviewImageChange={url => setEditing(current => current ? { ...current, previewImage: url } : current)} onExit={() => { setEditing(undefined); setEditingScheme(undefined); }} onSaveDocument={async document => { await browserAlbumApi.fontLayoutLibrary.update(editing.id, { name: document.basicInfo.templateName, previewImage: editing.previewImage, layers: document.layers }); message.success('字体布局已保存'); }} saveLocation="header" saveSuccessMessage="字体布局已保存" /></div>;
  const openCreate = () => { setName(''); setCreateShopId(shopId); setCreateCanvasRows(1); setCreateOpen(true); };
  const create = async () => { if (!name.trim() || createShopId === undefined) { message.warning('请输入字体布局名称并选择所属店铺'); return; } setSaving(true); try { const created = await browserAlbumApi.fontLayoutLibrary.create({ shopId: createShopId, productId: selectedProductId, name: name.trim(), sortKey: '', layers: blankLayers(createCanvasRows) }); setCreateOpen(false); setName(''); setEditingScheme(sizeFor(product)); setEditing(created); await load(); } catch (error) { message.error(error instanceof Error ? error.message : String(error)); } finally { setSaving(false); } };
  return <section className="panel template-library-page font-layouts-list-page"><div className="font-layouts-list-toolbar"><h1><Tag color="blue">{product.name}</Tag><span>字体布局数量 {templates.length}</span></h1><div className="font-layouts-list-actions"><Button type="primary" icon={<PlusOutlined />} onClick={openCreate}>新增字体布局</Button><Button icon={<ReloadOutlined spin={loading} />} loading={loading} onClick={() => setVersion(value => value + 1)}>刷新</Button></div></div>{loading || editorLoading ? <div className="template-library-loading"><Spin size="large" /></div> : templates.length ? <div className="template-library-grid">{templates.map(item => <LayoutCard key={item.id} template={item} onOpen={() => void openEditor(item)} />)}</div> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="当前产品暂无字体布局" />}<Modal className="font-layout-create-modal" open={createOpen} title="新增字体布局" okText="创建" cancelText="取消" confirmLoading={saving} okButtonProps={{ disabled: !name.trim() || createShopId === undefined }} onOk={() => void create()} onCancel={() => setCreateOpen(false)}><Form layout="vertical"><Form.Item label="所属店铺" required><Select showSearch optionFilterProp="label" value={createShopId} options={shops.map(shop => ({ value: shop.id, label: shop.shopName || shop.shop || '未命名店铺' }))} placeholder="选择店铺" onChange={setCreateShopId} /></Form.Item><Form.Item label="字体布局名称" required><Input autoFocus value={name} onChange={event => setName(event.target.value)} onPressEnter={() => void create()} placeholder="例如：封面标题字体布局" /></Form.Item><Form.Item label="画布排数" required extra="默认单排，只有像宣誓册一样的字体布局才选双排"><Segmented block value={createCanvasRows} options={[{ value: 1, label: '单排' }, { value: 2, label: '双排' }]} onChange={value => setCreateCanvasRows(value === 2 ? 2 : 1)} /></Form.Item></Form></Modal></section>;
}
